# Generated by Django 3.1 on 2020-08-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='products',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
